services:
  app:
    build: ./app
    container_name: java-webapp-architecture-app
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/java-webapp-architecture
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
    networks:
      - appnetwork 
  
  db:
    image: postgres:16
    container_name: java-webapp-architecture-db
    restart: always
    environment:
      POSTGRES_DB: java-webapp-architecture
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - appnetwork

volumes:
  pgdata:

networks:
  appnetwork:
